Update screenshots in user guide with latest UI
aws-samples/aws-ambit-scenario-designer-ue4 pull request #12
Opened 2021-12-14 21:41 UTC by rukekre

## What was the problem/requirement? (What/Why)
The user doc contained certain UI images that were older and didn't include newer functionality.

## What was the solution? (How)
Relevant screenshots have been updated in the user guide to match the latest UI. Changes have been made to the text to include any new information.

## What artifacts are related to this change?
Issues: (internal) P54511997

## What is the impact of this change?
Any users referring to the user guide will be provided with the latest information.

## Are you adding any new dependencies to the system?
No.

## How were these changes tested?
Locally, using the standard procedure to view changes to the user doc.

----
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-12-14 22:06 UTC, haozhao-aws reviewed
I am done with this round review. Only have one question about the order of the static obstacles.

2021-12-14 22:18 UTC, rukekre commented on docs/user-guide/mkdocs.yml
> +        - Spawn on Surface: spawn-on-surface.md
The order of the spawners in the user guide has been updated to match the order of the actors in Unreal Engine. Makes it easier for users to follow along.

2021-12-14 22:47 UTC, kris-work commented
Nit: `images/spawn-with-houdini/AmbitSpawnerForHoudini_UI_Annotated.png` doesn't fully match the style of other image annotations. The wrong font is used, font size relative to circle size is off, lines have rounded ends instead of square.

2021-12-14 22:48 UTC, kris-work commented
Nit: `/images/spawn-vehicle-path/AmbitVehiclePathGenerator_UI.png`: Annotations have visual artifacts that the other images don't. Specifically, aliasing of the circles. Also, the numbers in the circles are the wrong weight and aren't all centered well.

2021-12-14 22:52 UTC, kris-work commented
Images in `individual-scenario-generation.md`:

- Are red instead of our standard pink/purple
- Have square corners instead of rounded

2021-12-14 22:52 UTC, kris-work commented
Images in `bulk-senario-generation.md`:

Images in `individual-scenario-generation.md`:

- Are red instead of our standard pink/purple
- Have square corners instead of rounded
- Appear to be a different weight than used elsewhere

2021-12-14 22:53 UTC, kris-work commented
The file `bulk-senario-generation.md` has a typo in its name. It should be `bulk-scenario-generation.md`.

2021-12-14 22:57 UTC, kris-work requested changes
I'm going to insist on the highest standards here. Anything I've marked "nit" is at your discretion. But I'd like to see everything else addressed.

2021-12-14 22:57 UTC, kris-work commented on docs/user-guide/docs-source/spawn-in-volume.md
> +**Spawn in Volume** will use the <number-badge>3</number-badge> _density_ range and the <number-badge>5</number-badge> _rotation_ range you provide to instantiate copies of an Unreal Engine actor ran
"...Array of Unreal Engine actors...". "Array" is capitalized but "actors" isn't. We should be consistent. I suggest user lower case in most cases unless referring to a specific subclass type. So change "Array" -> "array" here.

2021-12-14 22:57 UTC, kris-work commented on docs/user-guide/docs-source/spawn-in-volume.md
> +**Spawn in Volume** will use the <number-badge>3</number-badge> _density_ range and the <number-badge>5</number-badge> _rotation_ range you provide to instantiate copies of an Unreal Engine actor ran
In most places, when referring to a param by it's label test we've been italicizing that text. Ex. "_Restrict to One Rotation_". But "Add Physics" hasn't been italicized here. Please italicize it both for consistency and better readability. Same applies to "Remove Overlaps".

2021-12-14 22:57 UTC, kris-work commented on docs/user-guide/docs-source/spawn-in-volume.md
> +**Spawn in Volume** will use the <number-badge>3</number-badge> _density_ range and the <number-badge>5</number-badge> _rotation_ range you provide to instantiate copies of an Unreal Engine actor ran
Capitalize "random seed" (number 9) to be consistent with other callouts.

2021-12-14 22:57 UTC, kris-work commented on docs/user-guide/docs-source/spawn-on-surface.md
> +This works by querying the simulation world for _surfaces_ that you specify. Surfaces can be indicated by <number-badge>1</number-badge> surface name pattern <number-badge>2</number-badge> and/or by
All the same consistency issues I called out for the `spawn-in-volume.md` should be applied here as well.

2021-12-15 21:54 UTC, rukekre reviewed
All concerns have been addressed. More images have been changed to increase consistency in the user guide.

2021-12-15 22:23 UTC, kris-work approved these changes

2021-12-15 22:27 UTC, merged